inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  Exclude:
    - lib/jekyll-admin/public/**/*
    - src/**/*
    - node_modules/**/*
    - Gemfile
    - jekyll-admin.gemspec

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/jekyll-admin/page_without_a_file.rb

Naming/UncommunicativeMethodParamName:
  Exclude:
    - lib/jekyll-admin/data_file.rb
