require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: '.rubocop.yml'

AllCops:
  Exclude:
    - lib/jekyll-admin/public/**/*
    - src/**/*
    - node_modules/**/*
    - vendor/**/*

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 9

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/jekyll-admin/page_without_a_file.rb
