inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  Exclude:
    - lib/jekyll-admin/public/**/*
    - src/**/*
    - node_modules/**/*
    - Gemfile
    - jekyll-admin.gemspec

Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
