language: ruby
rvm: 2.4
before_install:
  - nvm install 6
  - gem update --system --no-document
install: script/bootstrap
script: script/cibuild
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
env:
  matrix:
    - TEST_SUITE=node
    - TEST_SUITE=ruby
after_success:
  - npm run test:cover:CI
branches:
  only:
    - master
