import React, { Component, PropTypes } from 'react';
import TextareaAutosize from 'react-textarea-autosize';
import moment from 'moment';

export default class InputFilename extends Component {

  handleChange(e){
    const { onChange } = this.props;
    onChange(e.target.value);
  }

  render() {
    const { path, type } = this.props;

    let placeholder = 'example.md';
    if (type == 'posts') {
      const date = moment().format('YYYY-MM-DD');
      placeholder = `${date}-your-title.md`;
    } else if (type == 'datafiles') {
      placeholder = 'your-filename.yml';
    } else if (type == 'templates') {
      placeholder = 'example.html';
    }

    let tooltip, msg = null;
    if (type == 'templates') {
      msg = (
        <span className="tooltip-text">
          The Templates Index page lists only <b>directories</b>.
          Hence include the directory name as well when creating templates from
          the <b>Templates Index page</b>. e.g. <b>_layouts/archive.html</b>
        </span>
      );
    } else {
      msg = (
        <span className="tooltip-text">
          If you leave <b>path</b> blank, it will be autogenerated from title.
        </span>
      );
    }

    if (type != 'datafiles') {
      tooltip = (
        <span className="tooltip">
          <i className="fa fa-info-circle" aria-hidden="true" />
          {msg}
        </span>
      );
    }
    return (
      <div className="input-path">
        <label>Path {tooltip}</label>
        <TextareaAutosize
          key={path}
          onChange={(e) => this.handleChange(e)}
          placeholder={placeholder}
          defaultValue={path}
          ref="input" />
      </div>
    );
  }
}

InputFilename.propTypes = {
  path: PropTypes.string.isRequired,
  type: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired
};
