#!/bin/sh

set -e

echo "Running Node tests..."

# We want to run script/build on CI to ensure things actually build, but
# we don't want to have to run script/build locally every time we run tests
if [ -n "$CI" ]; then
  script/build
fi

npm test
